# Basic colors
foreground              #e1e2e9
background              #111318
selection_foreground    #d8e3f8
selection_background    #3c4758

# Cursor colors
cursor                  #a4c9fe
cursor_text_color       #00315c

# URL underline color when hovering with mouse
url_color               #d9bde3

# Kitty window border colors
active_border_color     #a4c9fe
inactive_border_color   #43474e
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #d3e3ff
active_tab_background   #1f4876
inactive_tab_foreground #c3c6cf
inactive_tab_background #1d2024
tab_bar_background      #111318

# Colors for marks
mark1_foreground #00315c
mark1_background #a4c9fe
mark2_foreground #263141
mark2_background #bcc7db
mark3_foreground #3c2946
mark3_background #d9bde3

# The 16 terminal colors
# black
color0 #43474e
color8 #8d9199

# red
color1 #ffb4ab
color9 #93000a

# green
color2  #a4c9fe
color10 #d3e3ff

# yellow
color3  #d9bde3
color11 #f5d9ff

# blue
color4  #bcc7db
color12 #d8e3f8

# magenta
color5  #1f4876
color13 #3a608f

# cyan
color6  #3c4758
color14 #543f5e

# white
color7  #c3c6cf
color15 #e1e2e9
